line-length = 88
indent-width = 4
target-version = "py311"
# Allow unused variables when underscore-prefixed.

[lint]
# Выключить правила, которые тебе не нужны
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501", "B008"]  # длинные строки, если используешь black
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
# Allow unused imports in __init__.py files.
"__init__.py" = ["F401"]
[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
