version: "3"
vars:
  CLUSTER: dev
  IMAGE: fastapi-kind:local

tasks:
  status:
    cmds:
      - kubectl get pods -A
      - kubectl get svc -A
      - kubectl get ingress -A
      - kubectl get nodes -A
      - kubectl -n app describe deploy web
  manifest:
    desc:
      "After change manifest"
    cmds:
      - kubectl apply -R -f k8s/

  reload_pod:
    desc:
      "After change code"
    cmds:
      - docker build -t app:local .
      - kind load docker-image app:local --name dev
      - kubectl -n app rollout restart deploy/web
      - kubectl -n app rollout status deploy/web

  run_k9s:
    desc: "k9s run"
    cmds:
      - k9s -n app

  cluster-info:
    desc: "cluster-info"
    cmds:
      - kubectl cluster-info

    # ===== Git commit with Ruff + push =====
  commit:
    desc: "Commit and push"
    vars:
      MSG: '{{.CLI_ARGS}}'
    preconditions:
      - sh: 'test -n "{{.MSG}}"'
        msg: 'Ошибка: Не указан комментарий. Использование: task commit -- "комментарий"'
    cmds:
      - "git add ."
      - 'git commit -m "{{.MSG}}" --no-verify'
      - "git push"
      - 'echo "Коммит успешно выполнен и отправлен."'
