version: "3"
vars:
  CLUSTER: dev
  IMAGE: fastapi-kind:local

tasks:
  create_cluster:
    desc: "Создать кластер kind с параметрами"
    vars:
      NAME: '{{.NAME | default "dev"}}'
      CONFIG: '{{.CONFIG | default "kind-config.yaml"}}'
    cmds:
      - kind create cluster --name {{.NAME}} --config {{.CONFIG}}

  remove_cluster:
    desc: "Удаление кластера"
    vars:
      NAME: '{{.NAME | default "dev"}}'
    cmds:
      - kind delete cluster --name {{.NAME}}

  deploy:
    desc:
      "After change yamls"
    cmds:
      - kubectl apply -f k8s/namespace.yaml
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
      - kubectl apply -f k8s/ingress.yaml
      - kubectl apply -f k8s/postgres-secret.yaml
      - kubectl apply -f k8s/postgres-svc.yaml
      - kubectl apply -f k8s/postgres-statefulset.yaml
      - kubectl -n app rollout status deploy/web
      - kubectl -n app get pods
      - kubectl -n app describe deploy web

  status:
    cmds:
      - kubectl get pods -A
      - kubectl get svc -A
      - kubectl get ingress -A
      - kubectl get nodes -A
      - kubectl -n app describe deploy web


  reload_pod:
    desc:
      "After change code"
    cmds:
      - docker build -t app:local .
      - kind load docker-image app:local --name dev
      - kubectl -n app rollout restart deploy/web
      - kubectl -n app rollout status deploy/web

  install_k9s:
    desc: "k9s install"
    cmds:
      - choco install -y k9s

  run_k9s:
    desc: "k9s run"
    cmds:
      - k9s -n app

  cluster-info:
    desc: "cluster-info"
    cmds:
      - kubectl cluster-info

  commit:
    desc: "Format with Ruff, commit with message, and push"
    vars:
      MSG: '{{.CLI_ARGS}}'
    preconditions:
      - sh: 'test -n "{{.MSG}}"'
        msg: 'Ошибка: Не указан комментарий. Использование: task commit -- "комментарий"'
    cmds:
      - "git add ."
      - 'git commit -m "{{.MSG}}" --no-verify'
      - "git push"
      - 'echo "Коммит успешно выполнен и отправлен."'
