"""add user id ro not

Revision ID: 20748feaf4ab
Revises: 8732484c7a5e
Create Date: 2025-07-29 14:34:55.942129

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20748feaf4ab"
down_revision: str | None = "8732484c7a5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notification_bindings", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_notification_bindings", "user_id")
    # ### end Alembic commands ###
