"""add field

Revision ID: 8732484c7a5e
Revises: fd7315c4a11f
Create Date: 2025-07-27 15:01:02.027309

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8732484c7a5e"
down_revision: str | None = "fd7315c4a11f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_sources",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
