"""add field

Revision ID: fd7315c4a11f
Revises: cf39c977fe2d
Create Date: 2025-07-27 14:59:29.370532

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd7315c4a11f"
down_revision: str | None = "cf39c977fe2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_sources", sa.Column("data_source_id", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_sources", "data_source_id")
    # ### end Alembic commands ###
