"""create api source model

Revision ID: 2697693da2ed
Revises: 7bfc8181fed8
Create Date: 2025-07-21 11:02:34.591394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2697693da2ed'
down_revision: Union[str, None] = '7bfc8181fed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('source_key', sa.String(length=255), server_default='default_key', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'source_key')
    # ### end Alembic commands ###
